[2025-02-28T03:10:16.959+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-02-28T03:00:00+00:00 [queued]>
[2025-02-28T03:10:16.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-02-28T03:00:00+00:00 [queued]>
[2025-02-28T03:10:16.983+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-28T03:10:17.020+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_to_postgres_file> on 2025-02-28 03:00:00+00:00
[2025-02-28T03:10:17.034+0000] {standard_task_runner.py:60} INFO - Started process 156 to run task
[2025-02-28T03:10:17.038+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_dag', 'load_to_postgres_file', 'scheduled__2025-02-28T03:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmp3zpa1lq0']
[2025-02-28T03:10:17.043+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask load_to_postgres_file
[2025-02-28T03:10:17.144+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_dag.load_to_postgres_file scheduled__2025-02-28T03:00:00+00:00 [running]> on host 5df4c2d19f78
[2025-02-28T03:10:17.274+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_file' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T03:00:00+00:00'
[2025-02-28T03:10:17.277+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-28T03:10:17.278+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/load_to_postgres.py']
[2025-02-28T03:10:17.295+0000] {subprocess.py:86} INFO - Output:
[2025-02-28T03:10:18.687+0000] {subprocess.py:93} INFO - [INFO] Đã tải file '2025/02/28/10-10-14.csv' từ MinIO
[2025-02-28T03:10:18.688+0000] {subprocess.py:93} INFO - [ERROR] Lỗi khi nạp dữ liệu vào Data Warehouse: invalid input syntax for type numeric: "{'times': 34.9534447868567, 'currency': 'btc', 'percentage': 3495.34447868567}"
[2025-02-28T03:10:18.688+0000] {subprocess.py:93} INFO - LINE 8: ...7573, 4878.26,  -55.5448, 0.432979, 500765.16063, '{''times'...
[2025-02-28T03:10:18.689+0000] {subprocess.py:93} INFO -                                                              ^
[2025-02-28T03:10:18.689+0000] {subprocess.py:93} INFO - 
[2025-02-28T03:10:18.690+0000] {subprocess.py:93} INFO - [INFO] Quá trình ETL hoàn tất. Đã xử lý 1 file mới từ MinIO.
[2025-02-28T03:10:18.782+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-28T03:10:18.809+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_dag, task_id=load_to_postgres_file, execution_date=20250228T030000, start_date=20250228T031016, end_date=20250228T031018
[2025-02-28T03:10:18.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-28T03:10:18.889+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
